/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.coreui;

public final class R {
    public static final class attr {
        public static final int font = 0x7f030095;
        public static final int fontProviderAuthority = 0x7f030097;
        public static final int fontProviderCerts = 0x7f030098;
        public static final int fontProviderFetchStrategy = 0x7f030099;
        public static final int fontProviderFetchTimeout = 0x7f03009a;
        public static final int fontProviderPackage = 0x7f03009b;
        public static final int fontProviderQuery = 0x7f03009c;
        public static final int fontStyle = 0x7f03009d;
        public static final int fontWeight = 0x7f03009e;
    }
    public static final class bool {
        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        public static final int notification_action_color_filter = 0x7f050049;
        public static final int notification_icon_bg_color = 0x7f05004a;
        public static final int ripple_material_light = 0x7f050055;
        public static final int secondary_text_default_material_light = 0x7f050057;
    }
    public static final class dimen {
        public static final int compat_button_inset_horizontal_material = 0x7f06004c;
        public static final int compat_button_inset_vertical_material = 0x7f06004d;
        public static final int compat_button_padding_horizontal_material = 0x7f06004e;
        public static final int compat_button_padding_vertical_material = 0x7f06004f;
        public static final int compat_control_corner_material = 0x7f060050;
        public static final int notification_action_icon_size = 0x7f060089;
        public static final int notification_action_text_size = 0x7f06008a;
        public static final int notification_big_circle_margin = 0x7f06008b;
        public static final int notification_content_margin_start = 0x7f06008c;
        public static final int notification_large_icon_height = 0x7f06008d;
        public static final int notification_large_icon_width = 0x7f06008e;
        public static final int notification_main_column_padding_top = 0x7f06008f;
        public static final int notificatio